channel: lb.h main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c
	icc -o channel -O3 main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c alloc.c 
	#icc -g -o channel main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c alloc.c
