channel: lb.h main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c
	icc -o channel -fast main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c
	#icc -g -o channel main.c func.c init.c lattice.c read_param.c fd_Q.c evolution.c

